version: '3'
services:
  streamlit:
    image: streamlit:latest
    build: ./app
    command: streamlit run streamlit_app/sentiment.py --server.port 8501
    volumes:
      - ./streamlit_app/:/app/streamlit_app
    ports:
    - 8501:8501